name: BadWordBlocker
main: surva\badwordblocker\BadWordBlocker
version: 1.2.17
api: 5.0.0

author: survanetwork
description: A chat filter which can block certain things
website: https://plugins.surva.net/#badwordblocker

commands:
  badwordblocker:
    description: "BadWordBlocker plugin main command"
    usage: "/badwordblocker <action>"
    permission: badwordblocker.manage
    aliases: ["bwb"]
permissions:
  badwordblocker.manage:
    description: "Manage settings/administrative actions of the BadWordBlocker plugin"
    default: op
  badwordblocker.bypass:
    description: "Bypass the chat filters of BadWordBlocker"
    default: op
  badwordblocker.bypass.swear:
    description: "Bypass blocking swear words in the chat"
    default: op
  badwordblocker.bypass.same:
    description: "Allows the write the same thing twice"
    default: op
  badwordblocker.bypass.spam:
    description: "Bypasses the spam protection so you can write as fast as you like"
    default: op
  badwordblocker.bypass.caps:
    description: "Bypasses the caps protection so you can write in caps"
    default: op
  badwordblocker.bypass.address:
    description: "Bypasses the web addresses (IP, domain, email) filter"
    default: op
